apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: tutorial-crud-angular
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
  selector:
    app: tutorial-crud-angular

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: tutorial-crud-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-crud-angular
  template:
    metadata:
      labels:
        app: tutorial-crud-angular
    spec:
      containers:
      - name: angular
        image: chrisc66/tutorial-crud:angular-frontend
        ports:
        - name: angular-port
          containerPort: 8081
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1500m
            memory: 2Gi
