apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: tutorial-crud
spec:
  ports:
  - port: 8081
    targetPort: 8081
  type: NodePort
  selector:
    role: angular

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: tutorial-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-crud
  template:
    metadata:
      labels:
        app: tutorial-crud
    spec:
      containers:
      - name: angular
        image: chrisc66/tutorial-crud:angular-frontend
        ports:
        - name: angular-port
          containerPort: 8081
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
