apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: tutorial-crud-django
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
  selector:
    app: tutorial-crud-django

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: tutorial-crud-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-crud-django
  template:
    metadata:
      labels:
        app: tutorial-crud-django
    spec:
      containers:
      - name: django
        image: chrisc66/tutorial-crud:django-backend
        ports:
        - name: django-port
          containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
