apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: tutorial-crud-mongo
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP 
  selector:
    app: tutorial-crud-mongo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: tutorial-crud-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-crud-mongo
  template:
    metadata:
      labels:
        app: tutorial-crud-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - name: mongo-port
          containerPort: 27017
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
